#pragma once

#include <cstdint>

// Stable application command identities exposed through the EUCON Key Commands
// processor. Enum values are internal dispatch values; EUCON assignments are
// preserved by the explicit persistence IDs in WindowsCommandProcessor.cpp.
enum class WindowsCommand : std::uint32_t
{
    OpenTaskManager,
    OpenTerminal,
    OpenPowerShell,
    OpenCommandPrompt,
    OpenRun,
    OpenFileExplorer,
    OpenControlPanel,
    OpenSystemInformation,
    OpenComputerManagement,
    OpenDeviceManager,
    OpenDiskManagement,
    OpenServices,
    OpenEventViewer,
    OpenRegistryEditor,
    OpenResourceMonitor,
    OpenCalculator,
    OpenNotepad,
    OpenPaint,
    OpenCharacterMap,
    OpenSnippingTool,
    OpenPowerUserMenu,
    OpenQuickAssist,
    OpenSoundOutputPanel,
    ToggleCalendarAndClock,
    OpenSystemAbout,

    OpenSettings,
    OpenWindowsUpdate,
    OpenSoundSettings,
    OpenVolumeMixer,
    OpenDisplaySettings,
    OpenNetworkSettings,
    OpenBluetoothSettings,
    OpenInstalledApps,
    OpenStartupApps,
    OpenDefaultApps,
    OpenStorageSettings,
    OpenPowerSettings,
    OpenDateTimeSettings,
    OpenClipboardSettings,
    OpenMicrophonePrivacy,
    OpenCameraPrivacy,
    OpenAccessibilitySettings,
    OpenPrinterSettings,
    OpenWindowsSecurity,

    OpenHomeFolder,
    OpenDesktopFolder,
    OpenDocumentsFolder,
    OpenDownloadsFolder,
    OpenMusicFolder,
    OpenPicturesFolder,
    OpenVideosFolder,
    OpenThisPC,
    OpenQuickAccess,
    OpenNetworkFolder,
    OpenRecycleBin,
    OpenRoamingAppData,
    OpenLocalAppData,
    OpenTempFolder,
    OpenStartupFolder,

    ExplorerExtraLargeIcons,
    ExplorerLargeIcons,
    ExplorerMediumIcons,
    ExplorerSmallIcons,
    ExplorerList,
    ExplorerDetails,
    ExplorerTiles,
    ExplorerContent,
    ExplorerNewFolder,
    ExplorerProperties,
    ExplorerTogglePreviewPane,
    ExplorerToggleDetailsPane,
    ExplorerPreviousFolder,
    ExplorerNextFolder,
    ExplorerParentFolder,
    ExplorerSearch,
    ExplorerFitColumns,

    OpenStart,
    OpenSearch,
    OpenQuickSettings,
    OpenNotifications,
    ShowDesktop,
    MinimizeAll,
    RestoreMinimized,
    OpenTaskView,
    SwitchNextWindow,
    SwitchPreviousWindow,
    MinimizeForegroundWindow,
    MaximizeRestoreForegroundWindow,
    CloseForegroundWindow,
    ToggleForegroundAlwaysOnTop,
    SnapWindowLeft,
    SnapWindowRight,
    SnapWindowUp,
    SnapWindowDown,
    MoveWindowNextMonitor,
    MoveWindowPreviousMonitor,
    OpenProjectDisplay,
    OpenCast,
    LockComputer,
    OpenSnapLayouts,
    SnapWindowTopHalf,
    SnapWindowBottomHalf,
    ToggleOtherWindowsMinimized,
    PeekDesktop,
    OpenWindowMenu,

    NewVirtualDesktop,
    CloseVirtualDesktop,
    NextVirtualDesktop,
    PreviousVirtualDesktop,

    OpenPinnedApp1,
    OpenPinnedApp2,
    OpenPinnedApp3,
    OpenPinnedApp4,
    OpenPinnedApp5,
    OpenPinnedApp6,
    OpenPinnedApp7,
    OpenPinnedApp8,
    OpenPinnedApp9,
    OpenPinnedApp10,
    NextTaskbarApp,
    PreviousTaskbarApp,
    FocusNotificationArea,

    Undo,
    Redo,
    Cut,
    Copy,
    Paste,
    SelectAll,
    Save,
    SaveAs,
    OpenFile,
    Find,
    Print,
    Rename,
    Escape,
    Enter,
    Delete,
    Backspace,
    NextField,
    PreviousField,
    ContextMenu,

    NewTab,
    CloseTab,
    ReopenClosedTab,
    NextTab,
    PreviousTab,
    FocusAddressBar,
    BrowserBack,
    BrowserForward,
    BrowserRefresh,
    NewWindow,
    FullScreen,
    ZoomIn,
    ZoomOut,
    ZoomReset,
    PageTop,
    PageBottom,
    PageUp,
    PageDown,

    MediaPlayPause,
    MediaNext,
    MediaPrevious,
    MediaStop,
    SystemVolumeMute,
    SystemVolumeUp,
    SystemVolumeDown,

    CaptureRegion,
    CaptureFullScreen,
    CaptureActiveWindow,
    ToggleGameBar,
    ToggleScreenRecording,
    VoiceTyping,
    EmojiPanel,
    ClipboardHistory,

    NextInputLanguage,
    PreviousInputLanguage,
    PreviousInputMethod,

    OpenOnScreenKeyboard,
    OpenMagnifier,
    CloseMagnifier,
    MagnifierZoomIn,
    MagnifierZoomOut,
    ToggleNarrator,
    ToggleColorFilters,

    FocusWindowsEucon,
    FocusUadEucon,
    FocusMackieControl,
};
