#pragma once
#include "WindowsCommand.h"
#include <string_view>

// Snapshot of the project's own 184 Windows commands. Intentionally independent
// of EUCON SDK types. See docs/MACKIE_RESEARCH.md for the staged shared-core plan.
struct MackieCommand
{
    const wchar_t* id;
    const wchar_t* category;
    const wchar_t* label;
    WindowsCommand command;
    int special; // 1 = mono audio, 2 = clear solo; zero = WindowsCommand
};
inline constexpr MackieCommand MackieCommands[] = {
    {L"MonoAudio", L"Windows Audio", L"Mono Audio", {}, 1},
    {L"ClearSolo", L"Windows Audio", L"Clear Solo", {}, 2},
    {L"OpenTaskManager", L"System Tools", L"Task Manager", WindowsCommand::OpenTaskManager, 0},
    {L"OpenTerminal", L"System Tools", L"Windows Terminal", WindowsCommand::OpenTerminal, 0},
    {L"OpenPowerShell", L"System Tools", L"PowerShell", WindowsCommand::OpenPowerShell, 0},
    {L"OpenCommandPrompt", L"System Tools", L"Command Prompt", WindowsCommand::OpenCommandPrompt, 0},
    {L"OpenRun", L"System Tools", L"Run", WindowsCommand::OpenRun, 0},
    {L"OpenFileExplorer", L"System Tools", L"File Explorer", WindowsCommand::OpenFileExplorer, 0},
    {L"OpenControlPanel", L"System Tools", L"Control Panel", WindowsCommand::OpenControlPanel, 0},
    {L"OpenSystemInformation", L"System Tools", L"System Information", WindowsCommand::OpenSystemInformation, 0},
    {L"OpenComputerManagement", L"System Tools", L"Computer Management", WindowsCommand::OpenComputerManagement, 0},
    {L"OpenDeviceManager", L"System Tools", L"Device Manager", WindowsCommand::OpenDeviceManager, 0},
    {L"OpenDiskManagement", L"System Tools", L"Disk Management", WindowsCommand::OpenDiskManagement, 0},
    {L"OpenServices", L"System Tools", L"Services", WindowsCommand::OpenServices, 0},
    {L"OpenEventViewer", L"System Tools", L"Event Viewer", WindowsCommand::OpenEventViewer, 0},
    {L"OpenRegistryEditor", L"System Tools", L"Registry Editor", WindowsCommand::OpenRegistryEditor, 0},
    {L"OpenResourceMonitor", L"System Tools", L"Resource Monitor", WindowsCommand::OpenResourceMonitor, 0},
    {L"OpenCalculator", L"System Tools", L"Calculator", WindowsCommand::OpenCalculator, 0},
    {L"OpenNotepad", L"System Tools", L"Notepad", WindowsCommand::OpenNotepad, 0},
    {L"OpenPaint", L"System Tools", L"Paint", WindowsCommand::OpenPaint, 0},
    {L"OpenCharacterMap", L"System Tools", L"Character Map", WindowsCommand::OpenCharacterMap, 0},
    {L"OpenSnippingTool", L"System Tools", L"Snipping Tool", WindowsCommand::OpenSnippingTool, 0},
    {L"OpenPowerUserMenu", L"System Tools", L"Power User Menu", WindowsCommand::OpenPowerUserMenu, 0},
    {L"OpenQuickAssist", L"System Tools", L"Quick Assist", WindowsCommand::OpenQuickAssist, 0},
    {L"OpenSoundOutputPanel", L"System Tools", L"Sound Output Panel", WindowsCommand::OpenSoundOutputPanel, 0},
    {L"ToggleCalendarAndClock", L"System Tools", L"Calendar and Clock", WindowsCommand::ToggleCalendarAndClock, 0},
    {L"OpenSystemAbout", L"System Tools", L"System About", WindowsCommand::OpenSystemAbout, 0},
    {L"OpenSettings", L"Settings", L"Settings", WindowsCommand::OpenSettings, 0},
    {L"OpenWindowsUpdate", L"Settings", L"Windows Update", WindowsCommand::OpenWindowsUpdate, 0},
    {L"OpenSoundSettings", L"Settings", L"Sound Settings", WindowsCommand::OpenSoundSettings, 0},
    {L"OpenVolumeMixer", L"Settings", L"Volume Mixer", WindowsCommand::OpenVolumeMixer, 0},
    {L"OpenDisplaySettings", L"Settings", L"Display Settings", WindowsCommand::OpenDisplaySettings, 0},
    {L"OpenNetworkSettings", L"Settings", L"Network Settings", WindowsCommand::OpenNetworkSettings, 0},
    {L"OpenBluetoothSettings", L"Settings", L"Bluetooth", WindowsCommand::OpenBluetoothSettings, 0},
    {L"OpenInstalledApps", L"Settings", L"Installed Apps", WindowsCommand::OpenInstalledApps, 0},
    {L"OpenStartupApps", L"Settings", L"Startup Apps", WindowsCommand::OpenStartupApps, 0},
    {L"OpenDefaultApps", L"Settings", L"Default Apps", WindowsCommand::OpenDefaultApps, 0},
    {L"OpenStorageSettings", L"Settings", L"Storage Settings", WindowsCommand::OpenStorageSettings, 0},
    {L"OpenPowerSettings", L"Settings", L"Power Settings", WindowsCommand::OpenPowerSettings, 0},
    {L"OpenDateTimeSettings", L"Settings", L"Date and Time", WindowsCommand::OpenDateTimeSettings, 0},
    {L"OpenClipboardSettings", L"Settings", L"Clipboard Settings", WindowsCommand::OpenClipboardSettings, 0},
    {L"OpenMicrophonePrivacy", L"Settings", L"Microphone Privacy", WindowsCommand::OpenMicrophonePrivacy, 0},
    {L"OpenCameraPrivacy", L"Settings", L"Camera Privacy", WindowsCommand::OpenCameraPrivacy, 0},
    {L"OpenAccessibilitySettings", L"Settings", L"Accessibility", WindowsCommand::OpenAccessibilitySettings, 0},
    {L"OpenPrinterSettings", L"Settings", L"Printers", WindowsCommand::OpenPrinterSettings, 0},
    {L"OpenWindowsSecurity", L"Settings", L"Windows Security", WindowsCommand::OpenWindowsSecurity, 0},
    {L"OpenHomeFolder", L"Folders", L"Home Folder", WindowsCommand::OpenHomeFolder, 0},
    {L"OpenDesktopFolder", L"Folders", L"Desktop", WindowsCommand::OpenDesktopFolder, 0},
    {L"OpenDocumentsFolder", L"Folders", L"Documents", WindowsCommand::OpenDocumentsFolder, 0},
    {L"OpenDownloadsFolder", L"Folders", L"Downloads", WindowsCommand::OpenDownloadsFolder, 0},
    {L"OpenMusicFolder", L"Folders", L"Music", WindowsCommand::OpenMusicFolder, 0},
    {L"OpenPicturesFolder", L"Folders", L"Pictures", WindowsCommand::OpenPicturesFolder, 0},
    {L"OpenVideosFolder", L"Folders", L"Videos", WindowsCommand::OpenVideosFolder, 0},
    {L"OpenThisPC", L"Folders", L"This PC", WindowsCommand::OpenThisPC, 0},
    {L"OpenQuickAccess", L"Folders", L"Quick Access", WindowsCommand::OpenQuickAccess, 0},
    {L"OpenNetworkFolder", L"Folders", L"Network", WindowsCommand::OpenNetworkFolder, 0},
    {L"OpenRecycleBin", L"Folders", L"Recycle Bin", WindowsCommand::OpenRecycleBin, 0},
    {L"OpenRoamingAppData", L"Folders", L"Roaming AppData", WindowsCommand::OpenRoamingAppData, 0},
    {L"OpenLocalAppData", L"Folders", L"Local AppData", WindowsCommand::OpenLocalAppData, 0},
    {L"OpenTempFolder", L"Folders", L"Temp Folder", WindowsCommand::OpenTempFolder, 0},
    {L"OpenStartupFolder", L"Folders", L"Startup Folder", WindowsCommand::OpenStartupFolder, 0},
    {L"ExplorerExtraLargeIcons", L"File Explorer", L"Extra Large Icons", WindowsCommand::ExplorerExtraLargeIcons, 0},
    {L"ExplorerLargeIcons", L"File Explorer", L"Large Icons", WindowsCommand::ExplorerLargeIcons, 0},
    {L"ExplorerMediumIcons", L"File Explorer", L"Medium Icons", WindowsCommand::ExplorerMediumIcons, 0},
    {L"ExplorerSmallIcons", L"File Explorer", L"Small Icons", WindowsCommand::ExplorerSmallIcons, 0},
    {L"ExplorerList", L"File Explorer", L"List", WindowsCommand::ExplorerList, 0},
    {L"ExplorerDetails", L"File Explorer", L"Details", WindowsCommand::ExplorerDetails, 0},
    {L"ExplorerTiles", L"File Explorer", L"Tiles", WindowsCommand::ExplorerTiles, 0},
    {L"ExplorerContent", L"File Explorer", L"Content", WindowsCommand::ExplorerContent, 0},
    {L"ExplorerNewFolder", L"File Explorer", L"New Folder", WindowsCommand::ExplorerNewFolder, 0},
    {L"ExplorerProperties", L"File Explorer", L"Properties", WindowsCommand::ExplorerProperties, 0},
    {L"ExplorerTogglePreviewPane", L"File Explorer", L"Toggle Preview Pane", WindowsCommand::ExplorerTogglePreviewPane, 0},
    {L"ExplorerToggleDetailsPane", L"File Explorer", L"Toggle Details Pane", WindowsCommand::ExplorerToggleDetailsPane, 0},
    {L"ExplorerPreviousFolder", L"File Explorer", L"Previous Folder", WindowsCommand::ExplorerPreviousFolder, 0},
    {L"ExplorerNextFolder", L"File Explorer", L"Next Folder", WindowsCommand::ExplorerNextFolder, 0},
    {L"ExplorerParentFolder", L"File Explorer", L"Parent Folder", WindowsCommand::ExplorerParentFolder, 0},
    {L"ExplorerSearch", L"File Explorer", L"Search Folder", WindowsCommand::ExplorerSearch, 0},
    {L"ExplorerFitColumns", L"File Explorer", L"Fit Columns to Content", WindowsCommand::ExplorerFitColumns, 0},
    {L"OpenStart", L"Window Management", L"Start Menu", WindowsCommand::OpenStart, 0},
    {L"OpenSearch", L"Window Management", L"Search", WindowsCommand::OpenSearch, 0},
    {L"OpenQuickSettings", L"Window Management", L"Quick Settings", WindowsCommand::OpenQuickSettings, 0},
    {L"OpenNotifications", L"Window Management", L"Notifications", WindowsCommand::OpenNotifications, 0},
    {L"ShowDesktop", L"Window Management", L"Show Desktop", WindowsCommand::ShowDesktop, 0},
    {L"MinimizeAll", L"Window Management", L"Minimize All", WindowsCommand::MinimizeAll, 0},
    {L"RestoreMinimized", L"Window Management", L"Restore Minimized", WindowsCommand::RestoreMinimized, 0},
    {L"OpenTaskView", L"Window Management", L"Task View", WindowsCommand::OpenTaskView, 0},
    {L"SwitchNextWindow", L"Window Management", L"Next Window", WindowsCommand::SwitchNextWindow, 0},
    {L"SwitchPreviousWindow", L"Window Management", L"Previous Window", WindowsCommand::SwitchPreviousWindow, 0},
    {L"MinimizeForegroundWindow", L"Window Management", L"Minimize Window", WindowsCommand::MinimizeForegroundWindow, 0},
    {L"MaximizeRestoreForegroundWindow", L"Window Management", L"Maximize or Restore", WindowsCommand::MaximizeRestoreForegroundWindow, 0},
    {L"CloseForegroundWindow", L"Window Management", L"Close Window", WindowsCommand::CloseForegroundWindow, 0},
    {L"ToggleForegroundAlwaysOnTop", L"Window Management", L"Toggle Always on Top", WindowsCommand::ToggleForegroundAlwaysOnTop, 0},
    {L"SnapWindowLeft", L"Window Management", L"Snap Left", WindowsCommand::SnapWindowLeft, 0},
    {L"SnapWindowRight", L"Window Management", L"Snap Right", WindowsCommand::SnapWindowRight, 0},
    {L"SnapWindowUp", L"Window Management", L"Snap Up", WindowsCommand::SnapWindowUp, 0},
    {L"SnapWindowDown", L"Window Management", L"Snap Down", WindowsCommand::SnapWindowDown, 0},
    {L"MoveWindowNextMonitor", L"Window Management", L"Move to Next Monitor", WindowsCommand::MoveWindowNextMonitor, 0},
    {L"MoveWindowPreviousMonitor", L"Window Management", L"Move to Previous Monitor", WindowsCommand::MoveWindowPreviousMonitor, 0},
    {L"OpenProjectDisplay", L"Window Management", L"Project Display", WindowsCommand::OpenProjectDisplay, 0},
    {L"OpenCast", L"Window Management", L"Cast", WindowsCommand::OpenCast, 0},
    {L"LockComputer", L"Window Management", L"Lock Computer", WindowsCommand::LockComputer, 0},
    {L"OpenSnapLayouts", L"Window Management", L"Snap Layouts", WindowsCommand::OpenSnapLayouts, 0},
    {L"SnapWindowTopHalf", L"Window Management", L"Snap Top Half", WindowsCommand::SnapWindowTopHalf, 0},
    {L"SnapWindowBottomHalf", L"Window Management", L"Snap Bottom Half", WindowsCommand::SnapWindowBottomHalf, 0},
    {L"ToggleOtherWindowsMinimized", L"Window Management", L"Isolate Current Window", WindowsCommand::ToggleOtherWindowsMinimized, 0},
    {L"PeekDesktop", L"Window Management", L"Peek at Desktop", WindowsCommand::PeekDesktop, 0},
    {L"OpenWindowMenu", L"Window Management", L"Window Menu", WindowsCommand::OpenWindowMenu, 0},
    {L"NewVirtualDesktop", L"Virtual Desktops", L"New Desktop", WindowsCommand::NewVirtualDesktop, 0},
    {L"CloseVirtualDesktop", L"Virtual Desktops", L"Close Desktop", WindowsCommand::CloseVirtualDesktop, 0},
    {L"NextVirtualDesktop", L"Virtual Desktops", L"Next Desktop", WindowsCommand::NextVirtualDesktop, 0},
    {L"PreviousVirtualDesktop", L"Virtual Desktops", L"Previous Desktop", WindowsCommand::PreviousVirtualDesktop, 0},
    {L"OpenPinnedApp1", L"Taskbar", L"Pinned App 1", WindowsCommand::OpenPinnedApp1, 0},
    {L"OpenPinnedApp2", L"Taskbar", L"Pinned App 2", WindowsCommand::OpenPinnedApp2, 0},
    {L"OpenPinnedApp3", L"Taskbar", L"Pinned App 3", WindowsCommand::OpenPinnedApp3, 0},
    {L"OpenPinnedApp4", L"Taskbar", L"Pinned App 4", WindowsCommand::OpenPinnedApp4, 0},
    {L"OpenPinnedApp5", L"Taskbar", L"Pinned App 5", WindowsCommand::OpenPinnedApp5, 0},
    {L"OpenPinnedApp6", L"Taskbar", L"Pinned App 6", WindowsCommand::OpenPinnedApp6, 0},
    {L"OpenPinnedApp7", L"Taskbar", L"Pinned App 7", WindowsCommand::OpenPinnedApp7, 0},
    {L"OpenPinnedApp8", L"Taskbar", L"Pinned App 8", WindowsCommand::OpenPinnedApp8, 0},
    {L"OpenPinnedApp9", L"Taskbar", L"Pinned App 9", WindowsCommand::OpenPinnedApp9, 0},
    {L"OpenPinnedApp10", L"Taskbar", L"Pinned App 10", WindowsCommand::OpenPinnedApp10, 0},
    {L"NextTaskbarApp", L"Taskbar", L"Next Taskbar App", WindowsCommand::NextTaskbarApp, 0},
    {L"PreviousTaskbarApp", L"Taskbar", L"Previous Taskbar App", WindowsCommand::PreviousTaskbarApp, 0},
    {L"FocusNotificationArea", L"Taskbar", L"Notification Area", WindowsCommand::FocusNotificationArea, 0},
    {L"Undo", L"Editing", L"Undo", WindowsCommand::Undo, 0},
    {L"Redo", L"Editing", L"Redo", WindowsCommand::Redo, 0},
    {L"Cut", L"Editing", L"Cut", WindowsCommand::Cut, 0},
    {L"Copy", L"Editing", L"Copy", WindowsCommand::Copy, 0},
    {L"Paste", L"Editing", L"Paste", WindowsCommand::Paste, 0},
    {L"SelectAll", L"Editing", L"Select All", WindowsCommand::SelectAll, 0},
    {L"Save", L"Editing", L"Save", WindowsCommand::Save, 0},
    {L"SaveAs", L"Editing", L"Save As", WindowsCommand::SaveAs, 0},
    {L"OpenFile", L"Editing", L"Open", WindowsCommand::OpenFile, 0},
    {L"Find", L"Editing", L"Find", WindowsCommand::Find, 0},
    {L"Print", L"Editing", L"Print", WindowsCommand::Print, 0},
    {L"Rename", L"Editing", L"Rename", WindowsCommand::Rename, 0},
    {L"Escape", L"Editing", L"Escape", WindowsCommand::Escape, 0},
    {L"Enter", L"Editing", L"Enter", WindowsCommand::Enter, 0},
    {L"Delete", L"Editing", L"Delete", WindowsCommand::Delete, 0},
    {L"Backspace", L"Editing", L"Backspace", WindowsCommand::Backspace, 0},
    {L"NextField", L"Editing", L"Next Field", WindowsCommand::NextField, 0},
    {L"PreviousField", L"Editing", L"Previous Field", WindowsCommand::PreviousField, 0},
    {L"ContextMenu", L"Editing", L"Context Menu", WindowsCommand::ContextMenu, 0},
    {L"NewTab", L"Browser and Tabs", L"New Tab", WindowsCommand::NewTab, 0},
    {L"CloseTab", L"Browser and Tabs", L"Close Tab", WindowsCommand::CloseTab, 0},
    {L"ReopenClosedTab", L"Browser and Tabs", L"Reopen Closed Tab", WindowsCommand::ReopenClosedTab, 0},
    {L"NextTab", L"Browser and Tabs", L"Next Tab", WindowsCommand::NextTab, 0},
    {L"PreviousTab", L"Browser and Tabs", L"Previous Tab", WindowsCommand::PreviousTab, 0},
    {L"FocusAddressBar", L"Browser and Tabs", L"Address Bar", WindowsCommand::FocusAddressBar, 0},
    {L"BrowserBack", L"Browser and Tabs", L"Back", WindowsCommand::BrowserBack, 0},
    {L"BrowserForward", L"Browser and Tabs", L"Forward", WindowsCommand::BrowserForward, 0},
    {L"BrowserRefresh", L"Browser and Tabs", L"Refresh", WindowsCommand::BrowserRefresh, 0},
    {L"NewWindow", L"Browser and Tabs", L"New Window", WindowsCommand::NewWindow, 0},
    {L"FullScreen", L"Browser and Tabs", L"Full Screen", WindowsCommand::FullScreen, 0},
    {L"ZoomIn", L"Browser and Tabs", L"Zoom In", WindowsCommand::ZoomIn, 0},
    {L"ZoomOut", L"Browser and Tabs", L"Zoom Out", WindowsCommand::ZoomOut, 0},
    {L"ZoomReset", L"Browser and Tabs", L"Reset Zoom", WindowsCommand::ZoomReset, 0},
    {L"PageTop", L"Browser and Tabs", L"Page Top", WindowsCommand::PageTop, 0},
    {L"PageBottom", L"Browser and Tabs", L"Page Bottom", WindowsCommand::PageBottom, 0},
    {L"PageUp", L"Browser and Tabs", L"Page Up", WindowsCommand::PageUp, 0},
    {L"PageDown", L"Browser and Tabs", L"Page Down", WindowsCommand::PageDown, 0},
    {L"MediaPlayPause", L"Media", L"Play or Pause", WindowsCommand::MediaPlayPause, 0},
    {L"MediaNext", L"Media", L"Next Track", WindowsCommand::MediaNext, 0},
    {L"MediaPrevious", L"Media", L"Previous Track", WindowsCommand::MediaPrevious, 0},
    {L"MediaStop", L"Media", L"Stop", WindowsCommand::MediaStop, 0},
    {L"SystemVolumeMute", L"Media", L"System Mute", WindowsCommand::SystemVolumeMute, 0},
    {L"SystemVolumeUp", L"Media", L"System Volume Up", WindowsCommand::SystemVolumeUp, 0},
    {L"SystemVolumeDown", L"Media", L"System Volume Down", WindowsCommand::SystemVolumeDown, 0},
    {L"CaptureRegion", L"Capture and Input", L"Screen Snip", WindowsCommand::CaptureRegion, 0},
    {L"CaptureFullScreen", L"Capture and Input", L"Save Full Screenshot", WindowsCommand::CaptureFullScreen, 0},
    {L"CaptureActiveWindow", L"Capture and Input", L"Copy Active Window", WindowsCommand::CaptureActiveWindow, 0},
    {L"ToggleGameBar", L"Capture and Input", L"Game Bar", WindowsCommand::ToggleGameBar, 0},
    {L"ToggleScreenRecording", L"Capture and Input", L"Screen Recording", WindowsCommand::ToggleScreenRecording, 0},
    {L"VoiceTyping", L"Capture and Input", L"Voice Typing", WindowsCommand::VoiceTyping, 0},
    {L"EmojiPanel", L"Capture and Input", L"Emoji Panel", WindowsCommand::EmojiPanel, 0},
    {L"ClipboardHistory", L"Capture and Input", L"Clipboard History", WindowsCommand::ClipboardHistory, 0},
    {L"NextInputLanguage", L"Input and Language", L"Next Input Language", WindowsCommand::NextInputLanguage, 0},
    {L"PreviousInputLanguage", L"Input and Language", L"Previous Input Language", WindowsCommand::PreviousInputLanguage, 0},
    {L"PreviousInputMethod", L"Input and Language", L"Previous Input Method", WindowsCommand::PreviousInputMethod, 0},
    {L"OpenOnScreenKeyboard", L"Accessibility", L"On-Screen Keyboard", WindowsCommand::OpenOnScreenKeyboard, 0},
    {L"OpenMagnifier", L"Accessibility", L"Open Magnifier", WindowsCommand::OpenMagnifier, 0},
    {L"CloseMagnifier", L"Accessibility", L"Close Magnifier", WindowsCommand::CloseMagnifier, 0},
    {L"MagnifierZoomIn", L"Accessibility", L"Magnifier Zoom In", WindowsCommand::MagnifierZoomIn, 0},
    {L"MagnifierZoomOut", L"Accessibility", L"Magnifier Zoom Out", WindowsCommand::MagnifierZoomOut, 0},
    {L"ToggleNarrator", L"Accessibility", L"Toggle Narrator", WindowsCommand::ToggleNarrator, 0},
    {L"ToggleColorFilters", L"Accessibility", L"Toggle Color Filters", WindowsCommand::ToggleColorFilters, 0},
};
inline const MackieCommand* FindMackieCommand(std::wstring_view id)
{
    for (const auto& command : MackieCommands) if (id == command.id) return &command;
    return nullptr;
}
